### ISSUE TITLE
Creating multiple segments quickly disabled SCRecorder.record()

### ISSUE THREAD

**Issue by huntermonk** [rFlex/SCRecorder#110] opened 2015-01-29 20:39 UTC
Hi,

First off - this is a great product and building with it has been a dream.

I've experienced a small bug. When creating many small segments (tapping the record button very quickly) the button will eventually not respond, and you will have to cancel the session.

It does not seem to matter what the number of total segments in the session are, just how quickly they are created in succession.

Let me know if there is anything I can do to help debug this or fix it.

Thanks,
Hunter

**Comment by rFlex** [comment] 2015-01-30 18:27
Do you manage to reproduce the bug on the sample?
What device and OS version do you have?

**Comment by huntermonk** [comment] 2015-01-30 19:36
Yes, I can replicate it on the sample. I've tested it using an iPhone 5s running iOS 8.1.3 and on a iPhone 4s running iOS 8.1.2.

I can send a video of the behavior if that would help.

**Comment by rFlex** [comment] 2015-01-30 20:47
I can't reproduce it on iPhone 5 too :/. Do you see anything helpful in the console? A video would be great! Thanks!

**Comment by huntermonk** [comment] 2015-01-30 21:50
Hi,

Here is the link to the video: https://www.dropbox.com/s/cvq1cvntrw5lnje/2015-01-30%2015.45.00.mov?dl=0

And here is the console output during:

2015-01-30 15:45:01.515 SCRecorderExamples[249:15664] Reconfigured audio input: (null)
2015-01-30 15:45:01.518 SCRecorderExamples[249:15664] Reconfigured video input: (null)
2015-01-30 15:45:01.531 SCRecorderExamples[249:15664] (null)
2015-01-30 15:45:01.531 SCRecorderExamples[249:15664] ==== Opened session ====
2015-01-30 15:45:01.532 SCRecorderExamples[249:15664] Session error: (null)
2015-01-30 15:45:01.532 SCRecorderExamples[249:15664] Audio error : (null)
2015-01-30 15:45:01.533 SCRecorderExamples[249:15664] Video error: (null)
2015-01-30 15:45:01.533 SCRecorderExamples[249:15664] Photo error: (null)
2015-01-30 15:45:01.534 SCRecorderExamples[249:15664] =======================
2015-01-30 15:45:05.482 SCRecorderExamples[249:15664] Began record segment: (null)
2015-01-30 15:45:05.766 SCRecorderExamples[249:15664] End record segment 0 at file:///private/var/mobile/Containers/Data/Application/D216F393-F3C9-4718-89DF-796965291601/tmp/1422654301SCVideo.0.mov: (null)
2015-01-30 15:45:08.745 SCRecorderExamples[249:15664] Reconfigured video input: (null)
2015-01-30 15:45:10.214 SCRecorderExamples[249:15664] Began record segment: (null)
2015-01-30 15:45:10.793 SCRecorderExamples[249:15664] End record segment 1 at file:///private/var/mobile/Containers/Data/Application/D216F393-F3C9-4718-89DF-796965291601/tmp/1422654301SCVideo.1.mov: (null)
2015-01-30 15:45:11.078 SCRecorderExamples[249:15664] Began record segment: (null)
2015-01-30 15:45:11.521 SCRecorderExamples[249:15664] End record segment 2 at file:///private/var/mobile/Containers/Data/Application/D216F393-F3C9-4718-89DF-796965291601/tmp/1422654301SCVideo.2.mov: (null)
2015-01-30 15:45:12.167 SCRecorderExamples[249:15664] Began record segment: (null)
2015-01-30 15:45:19.029 SCRecorderExamples[249:15664] Began record segment: (null)
2015-01-30 15:45:20.067 SCRecorderExamples[249:15664] End record segment 0 at file:///private/var/mobile/Containers/Data/Application/D216F393-F3C9-4718-89DF-796965291601/tmp/1422654317SCVideo.0.mov: (null)
2015-01-30 15:45:20.423 SCRecorderExamples[249:15664] Began record segment: (null)
2015-01-30 15:45:21.129 SCRecorderExamples[249:15664] End record segment 1 at file:///private/var/mobile/Containers/Data/Application/D216F393-F3C9-4718-89DF-796965291601/tmp/1422654317SCVideo.1.mov: (null)
2015-01-30 15:45:21.742 SCRecorderExamples[249:15664] Began record segment: (null)

**Comment by rFlex** [comment] 2015-02-08 00:23
Hey sorry for the very long delay. I'm so busy those days. It should be fixed now.

**Closed** 2015-02-08 00:23 UTC

**Comment by huntermonk** [comment] 2015-02-09 17:23
No worries!

However this fix does not work if _recorder.fastRecordMethodEnabled = YES;

Any way to get around that?
